ALTER TABLE ebooks
  ADD COLUMN free TINYINT(1) NOT NULL DEFAULT 0 AFTER status;

ALTER TABLE topics
  ADD COLUMN free TINYINT(1) NOT NULL DEFAULT 0 AFTER status;

ALTER TABLE exams
  ADD COLUMN free TINYINT(1) NOT NULL DEFAULT 0 AFTER status;

